name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: echo "Set up step (customize me)"

      - name: Run tests
        run: echo "Run tests here"

      - name: Build application
        run: echo "Build step here"
